# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json
backend:
  name: github
  repo: svgmap/hyperlayering.org
  branch: main
  base_url: https://sveltia-cms-auth.hla-201.workers.dev
  auth: [oauth]
  site_url: https://hyperlayering.org/
  preview_context: Cloudflare Workers

media_folder: /public/assets
public_folder: /assets

media_libraries:
  all: 
    filename_template: '{{year}}{{month}}{{day}}-{{uuid_short}}'
    slugify_filename: true
  default:
    config:
      transformations:
        raster_image:
          format: webp 
          quality: 100 
        svg:
          optimize: true

i18n:
  structure: multiple_folders
  locales: [en, ja]
  default_locale: en
  omit_default_locale_from_preview_path: true

collections:
  - name: updates
    label: Updates
    label_singular: Update
    icon: article
    folder: src/content/updates
    media_folder: "{{media_folder}}/updates"
    public_folder: "{{public_folder}}/updates"
    preview_path: "/{{locale}}/updates/{{slug}}"
    i18n: true
    fields:
      - name: title
        label: Title
        widget: text
        i18n: true
      - name: author
        label: Author
        widget: relation
        collection: authors
        value_field: "{{slug}}"
        display_fields: [name]
        search_fields: [name, bio]
        dropdown_threshold: 1
        i18n: duplicate
      - name: date
        label: Date
        widget: datetime
        type: date
        i18n: duplicate
      - name: description
        label: Description
        widget: text
        i18n: true
        maxlength: 250
      - name: showToc
        label: Show Table of Contents
        comment: Use Table of Contents for long posts only.
        widget: boolean
        default: false 
        i18n: duplicate
      - name: body 
        label: Body 
        widget: richtext 
        i18n: true
        buttons: 
          - bold
          - italic
          - strikethrough
          - code
          - link
          - heading-two
          - heading-three
          - heading-four
          - heading-five
          - heading-six
          - bulleted-list
          - numbered-list
          - quote
  - name: authors
    label: Authors
    label_singular: Author
    icon: person_edit
    duplicate: false
    media_folder: "{{media_folder}}/authors"
    public_folder: "{{public_folder}}/authors"
    folder: src/content/authors
    identifier_field: name
    format: json
    i18n: true
    fields: 
      - name: name
        label: Name
        widget: string
        i18n: duplicate
      - name: photo
        label: Photo
        widget: image
        required: false
        i18n: duplicate
      - name: bio
        label: Bio
        widget: text
        maxlength: 250
        required: false
        i18n: true
  - divider: true
  - name: guidelines
    label: Guidelines
    label_singular: Guideline
    icon: contract
    folder: src/content/guidelines
    media_folder: "{{media_folder}}/guidelines"
    public_folder: "{{public_folder}}/guidelines"
    preview_path: "/{{locale}}/guidelines/{{slug}}"
    i18n: true
    fields:
      - name: title
        label: Title
        widget: string
        i18n: true
      - name: lastUpdated
        label: Last Updated
        widget: datetime
        type: date
        i18n: duplicate
      - name: version
        label: Version
        widget: string
        i18n: duplicate
      - name: showToc
        label: Show Table of Contents
        comment: Use Table of Contents for long guidelines only.
        widget: boolean
        default: true
        i18n: duplicate 
      - name: body 
        label: Body 
        widget: richtext 
        i18n: true
        buttons: 
          - bold
          - italic
          - strikethrough
          - code
          - link
          - heading-two
          - heading-three
          - heading-four
          - heading-five
          - heading-six
          - bulleted-list
          - numbered-list
          - quote
  - divider: true
  - name: pages
    label: Pages
    label_singular: Page
    icon: web
    i18n: true
    files:
      - name: home
        label: Home Page
        i18n: true
        file: src/content/pages/{{locale}}/home.json
        fields:
          - name: hero
            label: Hero
            widget: object
            i18n: true
            fields: 
              - name: heading
                label: Heading
                widget: string
                i18n: true
              - name: subheading
                label: Subheading
                widget: string
                i18n: true            
          - name: aboutTitle
            label: About Section Header
            widget: text
            i18n: true
          - name: aboutHyperLayering 
            label: About Hyper Layering (Sections)
            widget: list 
            i18n: duplicate
            fields:
              - name: sectionTitle
                label: Section Title
                widget: string
                i18n: true
              - name: sectionBody
                label: Section Body
                widget: text
                i18n: true
          - name: aboutCloser
            label: About Hyper Layering Closer
            widget: text
            i18n: true
  - divider: true
  - name: navigation
    label: Navigation
    icon: menu
    i18n: true
    files:
      - name: footer
        label: Footer
        i18n: true
        file: src/content/navigation/{{locale}}/footer.json
        fields:
          - name: navGroup
            label: Navigation Group
            widget: list 
            i18n: duplicate 
            fields: 
            - name: groupTitle
              label: Navigation Group Title
              widget: string
              i18n: true
            - name: navLinks
              label: Navigation Group Links
              widget: list
              i18n: duplicate
              fields:
              - name: linkLabel
                label: Link Label
                widget: string
                i18n: true
              - name: isExternal
                label: Is External Link
                comment: Used to identify links that direct outside of hyperlayering.org
                widget: boolean
                i18n: duplicate
              - name: link
                label: Link / URL
                comment: For internal pages, provide the route only (eg. "/guidelines/page-id")
                widget: string
                pattern: 
                  - '^(?:https?:\/\/[^\s\/?#]+[^\s]*|\/(?!\/)[^\s]*)$'
                  - 'Must be an http(s) URL or a local path starting with a single "/"'
                i18n: duplicate