# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json
backend:
  name: github
  repo: svgmap/hyperlayering.org
  branch: cms-test-sveltia
  auth: [oauth]

media_folder: /public/assets
public_folder: /assets

i18n:
  structure: multiple_folders
  locales: [en, ja]
  default_locale: en

collections:
  - name: updates
    label: Updates
    label_singular: Update
    folder: src/updates
    i18n: true
    fields:
      - name: title
        label: Title
        widget: string
        i18n: true
      - name: author
        label: Author
        widget: string
        i18n: duplicate
      - name: date
        label: Date
        widget: datetime
        type: date
        i18n: duplicate
      - name: description
        label: Description
        widget: string
        i18n: true
      - name: body 
        label: Body 
        widget: richtext 
        i18n: true
